### ISSUE TITLE
Create an item pickup system

### ISSUE THREAD

**Issue by luustephen** [luustephen/SpaceRoguelikeDungeonRunner#11]
Have the player be able to pick up items and add them to a one way inventory (can only pick up items). also have a set of religion based items that can only contain one item and when picked up, replace the previous held religion item and drop it. There will be arm/chest/boot upgrades that will be part of the one way inventory. see pinned written notes.

**Comment by oscarzhang795** [comment]
I completed this already but I guess we can just roll with yours
